### PR TITLE
fix: fix strikethrough flanking rules

### LINKED ISSUE #3863: Tilde/strikethrough is not rendered the same way as GitHub
**Marked version:** 17.0.1

**Describe the bug**
The way tilde is handled doesn't match with how GitHub renders tilde.

**To Reproduce**

Paste the following into a markdown renderer
```
~1,~2

Between ~1.34 and ~5.4

Between (~1.34) and (~5.4)

Between ~1.34 and ~5.4
Between (~1.34) and (~5.4)
```
Permalink to markedjs
https://marked.js.org/demo/?text=~1%2C~2%0A%0ABetween%20~1.34%20and%20~5.4%0A%0ABetween%20(~1.34)%20and%20(~5.4)%0A%0ABetween%20~1.34%20and%20~5.4%0ABetween%20(~1.34)%20and%20(~5.4)&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=17.0.1

Permalink to CommonMark Dingus
https://spec.commonmark.org/dingus/?text=~1%2C~2%0A%0ABetween%20~1.34%20and%20~5.4%0A%0ABetween%20(~1.34)%20and%20(~5.4)%0A%0ABetween%20~1.34%20and%20~5.4%0ABetween%20(~1.34)%20and%20(~5.4)

Image

**Expected behavior**
Expected tilde to be handled the same way as how GitHub renders tilde. Example:

~1,~2

Between ~1.34 and ~5.4

Between (~1.34) and (~5.4)

Between ~1.34 and ~5.4
Between (~1.34) and (~5.4)

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 17.0.1

**Markdown flavor:** GitHub Flavored Markdown

## Description

Copy asterisk (`*`) emStrong flanking rules for tilde (`~`) strikethrough 

- Fixes #3863

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

File: src/Tokenizer.ts [hunk 1]
```diff
@@ -818,15 +818,56 @@ export class _Tokenizer<ParserOutput = string, RendererOutput = string> {
...
+        const text = raw.slice(lLength, -lLength);
+        return {
+          type: 'del',
+          raw,
+          text,
+          tokens: this.lexer.inlineTokens(text),
+        };
+      }
     }
   }
```
[the remark this answers is not in the document]
Comment (UziTech) [reply src/Tokenizer.ts:872]: Typically only keep code D.R.Y. if there are three or more instances. These are different enough that it would be more work keeping the differences from being broken if the code is updated.

File: src/Tokenizer.ts [hunk 2]
```diff
@@ -818,15 +818,56 @@ export class _Tokenizer<ParserOutput = string, RendererOutput = string> {
...
-        tokens: this.lexer.inlineTokens(cap[2]),
-      };
+  del(src: string, maskedSrc: string, prevChar = ''): Tokens.Del | undefined {
+    let match = this.rules.inline.delLDelim.exec(src);
+    if (!match) return;
+
+    const nextChar = match[1] || '';
+
+    if (!nextChar || !prevChar || this.rules.inline.punctuation.exec(prevChar)) {
+      // unicode Regex counts emoji as 1 char; spread into array for proper count
```
Comment (styfle) [inline src/Tokenizer.ts:828]: Do we have any tests with emoji?

Comment (UziTech) [reply src/Tokenizer.ts:828]: added some

File: test/specs/new/emoji_strikethrough.md [hunk 3]
```diff
@@ -0,0 +1,29 @@
+~~test 💁~~
```
Comment (styfle) [inline test/specs/new/emoji_strikethrough.md:1]:
```suggestion
~~🏴‍☠️~~

~~test 💁~~
```

File: test/specs/new/emoji_strikethrough.html [hunk 4]
```diff
@@ -0,0 +1,15 @@
+<p><del>test 💁</del></p>
```
Comment (styfle) [inline test/specs/new/emoji_strikethrough.html:1]:
```suggestion
<p><del>🏴‍☠️</del></p>
<p><del>test 💁</del></p>
```
