### PR TITLE
fix: fix autolink email after single space

### LINKED ISSUE #2072: Inconsistent token type for raw emails
**Marked version: 2.0.5**

**Describe the bug**
Only first raw email in markdown is treated as token type *link*, all other are treated as *text*.

**To Reproduce** 
1. Only one email in the markdown - treated as a token of type **link**: https://replit.com/@katafractari/CompassionateOurSandboxes
2. URL and an email in the markdown, email is treated as token of type **text**: https://replit.com/@katafractari/CompassionateOurSandboxes-1

**Expected behavior**
All emails should be treated as the same type of token.

Also in marked demo, the first email is treated as text type: https://marked.js.org/demo/?outputType=lexer&text=info%40email.io&options=&version=2.0.5

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 2.0.5

**Markdown flavor:** GitHub Flavored Markdown

## Description

fix autolink email after single space.

[failing demo](https://marked.js.org/demo/?outputType=html&text=%20info%40email.io&options=%7B%22gfm%22%3A%20true%7D&version=2.0.5)

fixes #2072 

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

File: src/rules.js [hunk 1]
```diff
@@ -286,7 +286,7 @@ inline.gfm = merge({}, inline.normal, {
   url: /^((?:ftp|https?):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^email/,
   _backpedal: /(?:[^?!.,:;*_~()&]+|\([^)]*\)|&(?![a-zA-Z0-9]+;$)|[?!.,:;*_~)]+(?!$))+/,
   del: /^(~~?)(?=[^\s~])([\s\S]*?[^\s~])\1(?=[^~]|$)/,
-  text: /^([`~]+|[^`~])(?:(?= {2,}\n)|[\s\S]*?(?:(?=[\\<!\[`*~_]|\b_|https?:\/\/|ftp:\/\/|www\.|$)|[^ ](?= {2,}\n)|[^a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-](?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@))|(?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@))/
+  text: /^([`~]+|[^`~])(?:(?= {2,}\n)|(?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@)|[\s\S]*?(?:(?=[\\<!\[`*~_]|\b_|https?:\/\/|ftp:\/\/|www\.|$)|[^ ](?= {2,}\n)|[^a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-](?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@)))/
```
Comment (UziTech) [inline src/rules.js:289]: I just moved the order of the look ahead before consuming more characters.

**Review by styfle — APPROVED** [review]

**Review by calculuschild — APPROVED** [review]
