### PR TITLE
Fixes ordered list ")" delimiter

### LINKED ISSUE #1700: Ordered list doesn't support ")" as delimiter
**Describe the bug**
Ordered list written as `1) item` is not recognized as a list.

**To Reproduce**
```md
1) a
2) b
```

<a href="https://spec.commonmark.org/dingus/?text=1)%20a%0A2)%20b%0A">commonmark</a> (link doesn't seem to work for me)
<a href="https://marked.js.org/demo/?text=1)%20a%0A2)%20b%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master">marked</a>

**Expected behavior**
If I am understanding the [spec](https://spec.commonmark.org/0.29/#lists) correctly, the `)` should be recognized as an ordered list delimiter.

### PR DESCRIPTION
**Pull request by jun-sheaf**
**Marked version:** Latest

**Markdown flavor:** CommonMark

## Description

- Fixes #1700

## Contributor

- [X] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

### CODE REVIEW

**Comment by UziTech** [comment]
Can you write a test to make sure no one breaks it in the future.

**Comment by jun-sheaf** [comment]
The tests have been included.

File: src/Tokenizer.js [hunk 1]
```diff
@@ -225,7 +225,7 @@ module.exports = class Tokenizer {
         // Remove the list item's bullet
         // so it is seen as the next token.
         space = item.length;
-        item = item.replace(/^ *([*+-]|\d+\.) */, '');
+        item = item.replace(/^ *([*+-]|\d+(?:\.|\))) */, '');
```
Comment (UziTech) [inline src/Tokenizer.js:228]:
```suggestion
        item = item.replace(/^ *([*+-]|\d+[.)]) */, '');
```

File: src/rules.js [hunk 2]
```diff
@@ -42,7 +42,7 @@ block.def = edit(block.def)
   .replace('title', block._title)
   .getRegex();
 
-block.bullet = /(?:[*+-]|\d{1,9}\.)/;
+block.bullet = /(?:[*+-]|\d{1,9}(?:\.|\)))/;
```
Comment (UziTech) [inline src/rules.js:45]:
```suggestion
block.bullet = /(?:[*+-]|\d{1,9}[.)])/;
```

easier to read

File: test/unit/Lexer-spec.js [hunk 3]
```diff
@@ -345,19 +345,27 @@ a | b
         md: `
 1. item 1
 2. item 2
+3) item 3
+4) item 4
```
Comment (UziTech) [inline test/unit/Lexer-spec.js:349]: This unit test actually goes against the spec [example 272](https://spec.commonmark.org/0.29/#example-272). marked should start a new list if the bullet or ordered list delimiter is changed.

I'm ok with not fixing that spec example in this PR but can you create an integration test instead of changing the unit test. You can create a new `.md` file and `.html` file in `/test/specs/new/`

something like:

list_paren_delimiter.md
```md
1) one
2) two
3) three


2) two
3) three
4) four
```

list_paren_delimiter.html
```html
<ol>
<li>one</li>
<li>two</li>
<li>three</li>
</ol>

<ol start="2">
<li>two</li>
<li>three</li>
<li>four</li>
</ol>
```

Comment (jun-sheaf) [reply test/unit/Lexer-spec.js]: I've made changes to accommodate ex.272. I am not too sure what the `shouldFail` keyword means in the CM tests, but some of them had to be removed. In any case, the fixes work well.

Comment (UziTech) [reply test/unit/Lexer-spec.js]: the `shouldFail` is there so we can track which spec tests are passing and which are failing.

**Comment by UziTech** [comment]
We require 2 Approvals for PRs so this will be merged when another team member approves it.

File: test/unit/Lexer-spec.js (hunk 3 above)
Comment (jun-sheaf) [reply test/unit/Lexer-spec.js]: So `shouldFail` means `shouldNotFailButDoesFail`?

Comment (UziTech) [reply test/unit/Lexer-spec.js]: exactly 😁👍
