### PR TITLE
fix: fix list item with blank first line

### LINKED ISSUE #2779: Lists with line breaks are not parsed correctly
**Marked version:**
[4.3.0](https://github.com/markedjs/marked/releases/tag/v4.3.0)
[4.2.3](https://github.com/markedjs/marked/releases/tag/v4.2.3)

**Describe the bug**

👋Hello. I am using marked and it is a great library, thank you for creating it.

According to [this discussion](https://github.com/markedjs/marked/discussions/1202#discussioncomment-4192078), V4.2.3 is supposed to be 100% compliant with the "Lists" and "List items" of the CommonMark standard. However, it seems to have some issues with parsing lists that contain line breaks, such as the following:
```
1.
Monday
2.
Tuesday
3.
Wednesday
```

**To Reproduce**

- [Marked Demo](https://marked.js.org/demo/?outputType=html&text=1.%0AMonday%0A2.%0ATuesday%0A3.%0AWednesday&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
   (3 list items)
- [CommonMark Demo](https://spec.commonmark.org/dingus/?text=1.%0AMonday%0A2.%0ATuesday%0A3.%0AWednesday)
   (an empty list item and a `<p>`)

**Expected behavior**

I believe that parsing it in the following way, like in CommonMark, is correct:
```
<ol>
<li></li>
</ol>
<p>Monday
2.
Tuesday
3.
Wednesday</p>
```

**Explanation**
According to [CommonMark 5.2 List items](https://spec.commonmark.org/0.30/#list-items):

1. A list may start or end with an empty list item. So `1.` is a list item with empty content.
2. In this case, the width `W` of the list marker (`1.`) is `2`, so in order for `Monday` to become the content of `1.`, it needs to have `3` (= `W + 1`) or more spaces of indentation. In the given example, since there are `0` spaces, `Monday` should become regular text (`<p>`).

Example1:
```
1.
Monday
```

Expected result:
```
<ol>
<li></li>
</ol>
<p>Monday</p>
```

Example2:
```
1.
   Monday
```

Expected result:
```
<ol>
<li>Monday</li>
</ol>
```

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** v13.0.1

**Markdown flavor:** CommonMark & GitHub Flavored Markdown

## Description

- Fixes #2779

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

File: src/Tokenizer.ts [hunk 1]
```diff
@@ -284,16 +284,18 @@ export class _Tokenizer {
...
           indent = indent > 4 ? 1 : indent; // Treat indented code blocks (> 4 spaces) as having only 1 indent
           itemContents = line.slice(indent);
           indent += cap[1].length;
         }
 
-        let blankLine = false;
+        let blankLine = !line.trim();
 
-        if (!line && /^ *$/.test(nextLine)) { // Items begin with at most one blank line
+        if (!line.trim() && /^ *$/.test(nextLine)) { // Items begin with at most one blank line
```
Comment (styfle) [inline src/Tokenizer.ts:298]:
```suggestion
        if (blankLine && /^ *$/.test(nextLine)) { // Items begin with at most one blank line
```
Can you reuse the variable?

I'm also curious if you can hoist line 296 up to line 281 so you can use the variable again on line 287.

**Review by styfle — APPROVED** [review]
