### PR TITLE
fix: blockquote code continuation

### LINKED ISSUE #3167: Lexer handling newlines incorrectly in some cases
**Marked version:**
11.1.1

**Describe the bug**
When using the lexer it seems to leave newlines at the end of some tokens instead of tokenizing them

**To Reproduce**
Input (hr):
```md
console.log(lexer.lex("---------------------------------\n\nhi"))
```
Output (hr):
```json
[
    {
        "type": "hr",
        "raw": "---------------------------------\n\n"
    },
    {
        "type": "paragraph",
        "raw": "hi",
        "text": "hi",
        "tokens": [
            {
                "type": "text",
                "raw": "hi",
                "text": "hi"
            }
        ]
    }
]
```

and input (blockquote):
```md
console.log(lexer.lex("> blockquote\n\nhi"))
```
Output (blockquote):
```json
[
    {
        "type": "blockquote",
        "raw": "> blockquote\n\n",
        "tokens": [
            {
                "type": "paragraph",
                "raw": "blockquote",
                "text": "blockquote",
                "tokens": [
                    {
                        "type": "text",
                        "raw": "blockquote",
                        "text": "blockquote"
                    }
                ]
            }
        ],
        "text": "blockquote"
    },
    {
        "type": "paragraph",
        "raw": "hi",
        "text": "hi",
        "tokens": [
            {
                "type": "text",
                "raw": "hi",
                "text": "hi"
            }
        ]
    }
]
```

For both of these examples you can see that the 2 newlines are being ignored and not tokenized by the lexer.
This is with `gfm: true` and `breaks: true`

**Expected behavior**
For hr input:
```json
[
    {
        "type": "hr",
        "raw": "---------------------------------"
    },
    {
        "type": "space",
        "raw": "\n\n"
    },
    {
        "type": "paragraph",
        "raw": "hi",
        "text": "hi",
        "tokens": [
            {
                "type": "text",
                "raw": "hi",
                "text": "hi"
            }
        ]
    }
]
```

For blockquote input:
```json
[
    {
        "type": "blockquote",
        "raw": "> blockquote",
        "tokens": [
            {
                "type": "paragraph",
                "raw": "blockquote",
                "text": "blockquote",
                "tokens": [
                    {
                        "type": "text",
                        "raw": "blockquote",
                        "text": "blockquote"
                    }
                ]
            }
        ],
        "text": "blockquote"
    },
    {
        "type": "br",
        "raw": "\n"
    },
    {
        "type": "paragraph",
        "raw": "hi",
        "text": "hi",
        "tokens": [
            {
                "type": "text",
                "raw": "hi",
                "text": "hi"
            }
        ]
    }
]
```

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 12.0.2

## Description

Fix blockquote continuation for code blocks

Fixes [CommonMark #236](https://spec.commonmark.org/0.31.2/#example-236)
Fixes [CommonMark #237](https://spec.commonmark.org/0.31.2/#example-237)

also adds space token after blockquote and hr if there are multiple newlines. fixes #3167.

I believe this will be a breaking change since tokens will change even though the output won't change.

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

File: src/Tokenizer.ts [hunk 1]
```diff
@@ -148,24 +148,87 @@ export class _Tokenizer {
...
+          const oldListToken = lastToken as Tokens.List;
+          const newText = oldListToken.raw + '\n' + lines.join('\n');
+          const newListToken = this.list(newText)!;
+          tokens[tokens.length - 1] = newListToken;
+
+          raw = raw.substring(0, raw.length - lastToken.raw.length) + newListToken.raw;
+          text = text.substring(0, text.length - oldListToken.raw.length) + newListToken.raw;
+          lines = newText.substring(tokens[tokens.length - 1].raw.length).split('\n');
+          continue;
+        }
```
Comment (calculuschild) [inline src/Tokenizer.ts:226]: This section seems to have some code duplication. Would it be useful to combine the logic for `list` and `blockquote` here a bit?

Just playing around with an example without actually testing, I'm thinking something like this:

```
    if (lastToken?.type === 'blockquote' || lastToken?.type === 'list') {
      const oldToken = lastToken as Tokens.Blockquote | Tokens.List;
      const newText = oldToken.raw + '\n' + lines.join('\n');
      const newToken = this[lastToken.type]!(newText);
      tokens[tokens.length - 1] = newToken;

      raw = raw.substring(0, raw.length - oldToken.raw.length) + newToken.raw;
      text = text.substring(0, text.length - oldToken.text.length) + newToken.text;
      if (lastToken.type === 'list') {
        lines = newText.substring(tokens[tokens.length - 1].raw.length).split('\n');
      }
    }
 ```

File: src/Tokenizer.ts [hunk 2]
```diff
@@ -148,24 +148,87 @@ export class _Tokenizer {
...
+      const tokens: Token[] = [];
+
+      while (lines.length > 0) {
+        let inBlockquote = false;
+        const currentLines = [];
+
+        while (lines.length > 0) {
+          // get lines up to a continuation
+          if (/^ {0,3}>/.test(lines[0])) {
+            currentLines.push(lines.shift());
```
Comment (calculuschild) [inline src/Tokenizer.ts:171]: Is there any performance concern for `.shift()` here with potentially many lines?

File: src/Tokenizer.ts [hunk 3]
```diff
@@ -148,24 +148,87 @@ export class _Tokenizer {
...
-      const top = this.lexer.state.top;
-      this.lexer.state.top = true;
-      const tokens = this.lexer.blockTokens(text);
-      this.lexer.state.top = top;
+      let lines = rtrim(cap[0], '\n').split('\n');
+      let raw = '';
+      let text = '';
+      const tokens: Token[] = [];
+
+      while (lines.length > 0) {
```
Comment (calculuschild) [inline src/Tokenizer.ts:164]: Also concerned that this seems to process *every* line in a document each time a blockquote rule is reached. Is there any other shortcut we should consider to break out of the loop early besides the check for `lastToken` at the end?

File: src/Tokenizer.ts (hunk 1 above)
Comment (UziTech) [reply src/Tokenizer.ts:226]: The `Tokens.Blockquote | Tokens.List` will mean we can't use `oldToken.text` since Tokens.List doesn't have a `text` property. And `text = text.substring(...` line is different between them.

I figured rather than peppering if statements for their differences it would be cleaner to duplicate some of the code. 

If there were more than two duplicates I think it would be worth it to create a method but DRY typically only helps when code is duplicated more than 3 times.

File: src/Tokenizer.ts (hunk 2 above)
Comment (UziTech) [reply src/Tokenizer.ts:171]: Good call! Probably better to not shift. I'll update that

File: src/Tokenizer.ts (hunk 3 above)
Comment (UziTech) [reply src/Tokenizer.ts:164]: This only processes every line that could be part of the blockquote. We already break on multiple new lines and hr and stuff

File: src/Tokenizer.ts (hunk 1 above)
Comment (calculuschild) [reply src/Tokenizer.ts:226]: In that case, what about reusing the same naming structure in each block for easier maintenance burden? The two are 90% identical, but this is difficult to see when `oldListToken` vs `oldBlockquoteToken` is making them appear more different than they are.

For me, it would be easier to visualize the differences between the two if the identical sections were also labeled identically.
