### PR TITLE
Fix auto-linking email

### LINKED ISSUE #1218: Code blocks with email-like text are no longer parsed as code
**Marked version:** 0.3.12 (OK) 0.3.14 (buggy)

```markdown
`user@host`
```

used to render as `<code>` block:

`user@host`

but now it's rendered as an e-mail link with literal `` ` `` in it:

[\`user@host\`](mailto:user@host)

### LINKED ISSUE #1307: Broken strikethrough of plain email text: ~~e@m.co~~
**Describe the bug**
When GFM is `true`, the following text:

    ~~hello@email.com~~

Renders as:

    <a href="mailto:~~hello@email.com">~~hello@email.com</a>~~

In HTML it thus shows up as _something like_ (but not exactly, the mailto should render as above - see the Markdown demo for exact behaviour, Github's parser is harder to coerce to the invalid rendering):

<a href="mailto:~~hello@email.com">~~hello@email.com</a>\~\~

**To Reproduce**

Simply type `~~hello@email.com~~` into the Demo.

**Expected behavior**
Expect the following output

    <del><a href="mailto:hello@email.com">hello@email.com</a></del>

### LINKED ISSUE #1327: Autolink breaks mailto links when wrapped in styling syntax
In versions v0.3.14 and up, when wrapping an email address with styling syntax (*, **, _, etc), Marked includes the opening syntax in the email address, which prevents styling. ex: `**me@example.com**` renders `<a href='mailto:**me@example.com'>**me@example.com</a>**`

**Steps to reproduce the behavior:**

1. Install any version of Marked from v0.3.14 until latest (`npm install marked`)
2. Wrap an email address in bold or italic syntax (`**me@example.com**`)
3. Render with Marked (`var marked = require('marked'); marked('**me@example.com**')`)
4. Actual output is `<a href='mailto:**me@example.com'>**me@example.com</a>**`

**Expected behavior**
Marked should properly style the email address and extract it correctly for the mailto link: `<strong><a href='mailto:me@example.com'>me@example.com</a></strong>`

### PR DESCRIPTION
**Pull request by Feder1co5oave**
**Markdown flavor:** GitHub Flavored

## Description

Fixes #1218 (see [comment](https://github.com/markedjs/marked/issues/1218#issuecomment-422518372))
Fixes #1307
Fixes #1327

I believe this complies better with the gfm spec.

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR)

### CODE REVIEW

**Comment by styfle** [comment]
This looks like a duplicate of PR #1337
I think I prefer #1337 because it fixes several bugs 😃

**Comment by Feder1co5oave** [comment]
@styfle see https://github.com/markedjs/marked/issues/1218#issuecomment-422520406

**Comment by Feder1co5oave** [comment]
updated fix list

**Comment by styfle** [comment]
I didn't realize this fixes the strikethough and bold bugs too! Let me take a look again.

File: lib/marked.js [hunk 1]
```diff
@@ -616,6 +615,9 @@ inline.gfm = merge({}, inline.normal, {
     .getRegex()
 });
 
+inline.gfm.url = edit(inline.gfm.url)
+  .replace('email', inline.gfm._extended_email)
+  .getRegex();
```
Comment (styfle) [inline lib/marked.js]: Why was this moved? It looks like the only change to the previous code was `inline._email` changed to `inline.gfm._extended_email`

Comment (Feder1co5oave) [reply lib/marked.js]: Those two email regexes are similar, but different. It was moved out of the block because I had no way of referencing inline.gfm._extended_email from _inside_ the block.

**Comment by styfle** [comment]
Alright I'll go ahead and merge this
