### PR TITLE
fix: non leading-tabs in markdown content (#1559)

### LINKED ISSUE #1559: Markdown containing tabs not converted properly to spaces
**Describe the bug**
The package converts the tabs in the markdown to 4 spaces every time. It breaks the alignment of the text. It's not how tabs work. The tab indentation of the current tab in a string will be 
`tabsize - ((number of characters occupied in current tab buffer) % tabsize)`

image

**To Reproduce**
Steps to reproduce the behaviour:

1. Type any text using tabs.
2. Paste it in [Marked Demo](https://marked.js.org/demo/) for viewing parsed HTML. You will see changes in the alignment.

Below is the text that contains tabs that I am parsing to HTML.
```markdown
# markdown alignment

```
        [FirstName]				=> TEST
        [LastName]				=> TESTIN
        [EmailAddress]			=> TEST
        [CompanyName]			=> Test Company
        [Phone]					=> TEST
```
```

Demo links:
1. [Marked Demo](https://marked.js.org/demo/?text=%23%20markdown%20alignment%0A%0A%60%60%60%0A%20%20%20%20%20%20%20%20%5BFirstName%5D%09%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BLastName%5D%09%09%09%09%3D%3E%20TESTIN%0A%20%20%20%20%20%20%20%20%5BEmailAddress%5D%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BCompanyName%5D%09%09%09%3D%3E%20Test%20Company%0A%20%20%20%20%20%20%20%20%5BPhone%5D%09%09%09%09%09%3D%3E%20TEST%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%23%20markdown%20alignment%0A%0A%60%60%60%0A%20%20%20%20%20%20%20%20%5BFirstName%5D%09%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BLastName%5D%09%09%09%09%3D%3E%20TESTIN%0A%20%20%20%20%20%20%20%20%5BEmailAddress%5D%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BCompanyName%5D%09%09%09%3D%3E%20Test%20Company%0A%20%20%20%20%20%20%20%20%5BPhone%5D%09%09%09%09%09%3D%3E%20TEST%0A%60%60%60)

The CommonMark was also not able to parse the tabs to appropriate number od spaces.

The [ParseDown](https://packagist.org/packages/erusev/parsedown) PHP package was able to parse the tabs in text to appropriate number of spaces. Its how any user will expect the HTML output to look like. You can paste the above given markdown text in [ParseDown Demo](https://parsedown.org/demo)
image

**Expected behavior**
When I am writing a markdown containing tabs, I will expect it to give the same alignment when converted to HTML. It how any user will expect.

I am using this text:
image

The arrows aren't aligned upon parsing. It gets  parsed to HTML like this:
image
image

While, any user will expect it to be like this:
image

### PR DESCRIPTION
**Pull request by rossipedia**
**Marked version:**

**Markdown flavor:** CommonMark

## Description

Only replaces tabs at the beginning of a block construct. Tabs in the middle of the item are unaffected.

- Fixes #1559 (if fixing a known issue; otherwise, describe issue using the following format)

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

File: src/Lexer.js [hunk 1]
```diff
@@ -135,6 +134,15 @@ export class Lexer {
     if (this.options.pedantic) {
       src = src.replace(/^ +$/gm, '');
     }
+
+    if (this.options.gfm || this.options.pedantic) {
```
Comment (UziTech) [inline src/Lexer.js:138]: gfm should act for the most part like commonmark.

```suggestion
    if (this.options.pedantic) {
```

**Review by UziTech — CHANGES_REQUESTED** [review]

File: src/Lexer.js (hunk 1 above)
Comment (rossipedia) [reply src/Lexer.js:138]: That causes a test failure, I'll see if I can't suss out how to address it:

```
Failures:
1) New html_comments should pass
  Message:
    Expected: Example 10</h3><!-- multi
    line    
    comment
    --><h3 id="exampl
      Actual: Example 10</h3><!-- multi
    line	
    comment
    --><h3 id="example-1
```

Comment (UziTech) [reply src/Lexer.js:138]: It looks like you will have to change https://github.com/markedjs/marked/blob/master/test/specs/new/html_comments.html#L40

replace the spaces at the end of the line with a tab

Comment (rossipedia) [reply src/Lexer.js]: Looks like there was a tab character at the end of the multiline comment in `new/html_comments.md`, and the test was expecting it to be converted to 4 spaces. With this change in behavior, I believe the expected output (`html_comments.html`) should be updated to expect that the tab character be preserved instead since it's not a leading tab.

**Comment by rossipedia** [comment]
Does this look good now?

File: src/Lexer.js [hunk 2]
```diff
@@ -135,6 +134,15 @@ export class Lexer {
     if (this.options.pedantic) {
       src = src.replace(/^ +$/gm, '');
     }
+
+    if (this.options.pedantic) {
```
Comment (UziTech) [inline src/Lexer.js:138]: Can you combine this if statement with the one above? I think we should do the tab conversion before replacing a line with only spaces with a blank line.

**Review by UziTech — CHANGES_REQUESTED** [review]

**Review by UziTech — APPROVED** [review]
Thanks for fixing this! 💯

**Review by calculuschild — APPROVED** [review]
Looks good to me. Only question is if there might be some other token that needs its `rules.js` updated to handle tabs?

**Review by UziTech — CHANGES_REQUESTED** [review]
I did find one example that seems broken.

```markdown
>	test
// tab between > and test
```

It is actually currently kind of broken (additional spaces are added to the output) but with this PR it creates a code element in the blockquote.

Looks like https://github.com/markedjs/marked/blob/master/src/Tokenizer.js#L154 might have to be updated to remove a tab after `>` as well.

**Comment by rossipedia** [comment]
Ok seems like that might be a case that's missing a test. I'll see about putting one together for it.

**Review by UziTech — APPROVED** [review]

**Comment by UziTech** [comment]
@calculuschild I think this now passes any test I can think of.

**Review by calculuschild — APPROVED** [review]
Cool, I approve then. I can't think of anything else either.
