### PR TITLE
fix: Total rework of Emphasis/Strong

### LINKED ISSUE #1811: Asterisks are not properly escaped
**Marked version:** 1.1.0, 1.2.1, and current master

**Describe the bug**
`*text\* 1234*` should be rendered to "*text\* 1234*", not "*text\\* 1234\*".

This issue is originally posted at https://github.com/markedjs/marked/issues/520#issuecomment-137831487

**To Reproduce**

[Demo](https://marked.js.org/demo/?text=*test%5C*%20123*&options=%7B%20%22baseUrl%22%3A%20null%2C%20%22breaks%22%3A%20false%2C%20%22gfm%22%3A%20true%2C%20%22headerIds%22%3A%20true%2C%20%22headerPrefix%22%3A%20%22%22%2C%20%22highlight%22%3A%20null%2C%20%22langPrefix%22%3A%20%22language-%22%2C%20%22mangle%22%3A%20true%2C%20%22pedantic%22%3A%20false%2C%20%22sanitize%22%3A%20false%2C%20%22sanitizer%22%3A%20null%2C%20%22silent%22%3A%20false%2C%20%22smartLists%22%3A%20false%2C%20%22smartypants%22%3A%20false%2C%20%22tokenizer%22%3A%20null%2C%20%22walkTokens%22%3A%20null%2C%20%22xhtml%22%3A%20false%7D&version=master)

### LINKED ISSUE #1860: em and strong (***〜***)
Thanks for the great project.

When em and strong are used together, there appears to be a difference in the analysis results.
At the beginning of a line, em and strong are parsed properly, but in a sentence, they are not.
Is this as expected? We would be happy to confirm it when you have time.

The following link is for your reference.

https://marked.js.org/demo/?text=AAAAAAAA***AA***AAAA%0A%0A***AA***AAAAAAAAAAAA%0A%0A***AA***AAAAAA***AAA***AAA%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

### PR DESCRIPTION
**Pull request by calculuschild**
## Description

- Fixes #1860, Fixes #1811 
- Also fixes Commonmark/GFM examples: 
  - (em & strong) 361, 387, 388, 407, 412, 415, 416, 424, 425, 442, 445, 446, 453, 455, 456, 457, 465, 466, 467, 470
  - This puts us up to 100% compatibility with commonmark specs!

- Noticeable speedup, especially on the GFM benchmark (~8.7 sec -> ~8.1 sec, pretty consistent over 5 runs on my laptop)

## What was attempted

1) Simplify regex for em & strong, combined now into a single tokenizer
2) When masking the `src` string in Lexer, also mask out escaped `\*` and `\_` which further simplifies a lot of regex
3) Track total opening delimiter characters vs closing characters, and ensure they match
4) More closely follow CommonMark spec:
   * Favor `<em><strong>text</strong></em>` over `<strong><em>text</em></strong>`
   * Correct some of the "New" spec tests that had this ^ swapped incorrectly (and delete one that is redundant now)
   * Handle em/strong CommonMark [rules 9-10](https://spec.commonmark.org/0.29/#can-open-emphasis), that left and right delimiters cannot sum to a multiple of 3, unless each is a multiple of 3
   * Handle cases with lots of extra unmatched delimiters, e.g. `*text*********`

Note this involves significant changes in the Lexer and Tokenizer APIs, which should be noted in the update.

The new Regex should be pretty benign compared to the earlier stuff. It literally checks for sequences of the pattern `a***b`, that is, runs of `*` or `_` between a single character on each side.

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

File: src/Lexer.js [hunk 1]
```diff
@@ -393,16 +399,8 @@ module.exports = class Lexer {
...
-        src = src.substring(token.raw.length);
-        token.tokens = this.inlineTokens(token.text, [], inLink, inRawBlock);
-        tokens.push(token);
-        continue;
-      }
-
-      // em
-      if (token = this.tokenizer.em(src, maskedSrc, prevChar)) {
+      // em & strong
+      if (token = this.tokenizer.emStrong(src, maskedSrc, prevChar)) {
```
Comment (UziTech) [inline src/Lexer.js:403]: This would definitely be a breaking change since the tokenizers are part of the public API. Can we do this without combining them? Can we just switch the order of em and strong to get `<strong><em>a</em></strong>` to switch to `<em><strong>a</strong></em>`?

Comment (calculuschild) [reply src/Lexer.js:403]: Unfortunately, they kind of need to be tackled together to get the right sequence of `<em><strong>` to work, which isn't just a stylistic thing. Even though it renders the same as `<strong><em>`, the processing to get to that point also clears up several other bugs, especially regarding uneven `**text*****` delimiters on both sides.

Comment (UziTech) [reply src/Lexer.js:403]: After researching quite a few dependants I think it should be fine to combine them since most dependants will change the renderer instead of the tokenizer. This will have to be a major bump to v2 though. I do want to get a few other breaking changes together before releasing v2 so it might be a while before I get to fully reviewing this PR.

Comment (calculuschild) [reply src/Lexer.js:403]: That sounds appropriate. I need to review the other PRs you have waiting as well that should go out before this anyway...

There are some other changes I've seen in the issues list that I'd like to lump into a v2 bump as well.

File: lib/marked.js [hunk 2]
```diff
@@ -926,6 +926,7 @@
       }
 
       var match = this.rules.inline.strong.start.exec(src);
+      console.log(match);
```
Comment (styfle) [inline lib/marked.js:929]: Remove console.log()

File: lib/marked.esm.js [hunk 3]
```diff
@@ -824,6 +824,8 @@ var Tokenizer_1 = class Tokenizer {
   strong(src, maskedSrc, prevChar = '') {
     let match = this.rules.inline.strong.start.exec(src);
 
+    console.log(match);
```
Comment (styfle) [inline lib/marked.esm.js:827]: Remove console.log()

File: lib/marked.js (hunk 2 above)
Comment (UziTech) [reply lib/marked.js:929]: lib will get regenerated once it is merged but /lib and min scripts should probably be removed from the PR

Comment (calculuschild) [reply lib/marked.js:929]: I forgot to exclude the libs. I will do that.

Comment (calculuschild) [reply lib/marked.js]: I undid the changes on the lib files so they aren't part of the PR.

File: lib/marked.esm.js (hunk 3 above)
Comment (calculuschild) [reply lib/marked.esm.js]: Removed this file from the PR.

File: src/Tokenizer.js [hunk 4]
```diff
@@ -507,46 +507,53 @@ module.exports = class Tokenizer {
...
-  strong(src, maskedSrc, prevChar = '') {
-    let match = this.rules.inline.strong.start.exec(src);
+  emStrong(src, maskedSrc, prevChar = '') {
+    let match = this.rules.inline.emStrong.lDelim.exec(src);
+    if (!match) return;
 
-    if (match && (!match[1] || (match[1] && (prevChar === '' || this.rules.inline.punctuation.exec(prevChar))))) {
-      maskedSrc = maskedSrc.slice(-1 * src.length);
-      const endReg = match[0] === '**' ? this.rules.inline.strong.endAst : this.rules.inline.strong.endUnd;
+    if (match[3] && prevChar.match(/[\p{L}\p{N}]/u)) return; // _ can't be be between two alphanumerics. \p{L}\p{N} includes non-english alphabet/numbers as well
```
Comment (styfle) [inline src/Tokenizer.js:514]:
```suggestion
    if (match[3] && prevChar.match(/[\p{L}\p{N}]/u)) return; // _ can't be between two alphanumerics. \p{L}\p{N} includes non-english alphabet/numbers as well
```

**Comment by calculuschild** [comment]
100% em\strong compliance!

**Comment by UziTech** [comment]
I added a test for #1927 to make sure it is not regressed in the future.

**Review by UziTech — APPROVED** [review]

**Comment by UziTech** [comment]
@styfle We should get this and #1926 released as v2 soon. This PR fixes the security issue in #1927

**Review by styfle — APPROVED** [review]
