### PR TITLE
fix: fix emstrong unicode

### LINKED ISSUE #3069: Bold hyper link with two * symbols causes one to be visible after parsing and removes space
**Marked version: 9.1.4**

**Describe the bug**
Writing bold hyper links with two * symbols results in the last symbol being visible and also removes the space between the last * symbol and the next character.

**To Reproduce**

- Use marked from jsdelivr

```html
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    marked.parse("**[🤖┃bot-commands](https://discord.com/channels/870575002536280074/981392899012980796)** hello") // Output: <strong><a href="https://discord.com/channels/870575002536280074/981392899012980796">🤖┃bot-commands</a>*</strong> | rendered: 🤖┃bot-commands*hello
</script>
```

Rendered result:
image

**Expected behavior**
The parser should not include the last * symbol in the output which means the result should be <strong><a href="https://discord.com/channels/870575002536280074/981392899012980796">🤖┃bot-commands</a></strong>

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 9.1.4

## Description

Fix unicode emstrong [demo](https://marked-website-git-fork-uzitech-fix-emstrong-unicode-markedjs.vercel.app/demo/?text=**%5B%F0%9F%A4%96%E2%94%83bot-commands%5D(https%3A%2F%2Fdiscord.com%2Fchannels%2F870575002536280074%2F981392899012980796)**%20hello&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=master)

- Fixes #3069

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Review by calculuschild — APPROVED** [review]
Looks good.

File: src/Tokenizer.ts [hunk 1]
```diff
@@ -654,8 +654,7 @@ export class _Tokenizer {
 
         // Remove extra characters. *a*** -> *a*
         rLength = Math.min(rLength, rLength + delimTotal + midDelimTotal);
-
-        const raw = [...src].slice(0, lLength + match.index + rLength + 1).join('');
+        const raw = src.slice(0, lLength + match.index + rLength + [...match[0]][0].length);
```
Comment (styfle) [inline src/Tokenizer.ts:657]: Is the spread necessary here?

Comment (UziTech) [reply src/Tokenizer.ts:657]: Yes, that is so unicode character length is calculated correctly.

Comment (styfle) [reply src/Tokenizer.ts:657]: It might be good to add a comment here since it’s not obvious

**Review by styfle — APPROVED** [review]
