### PR TITLE
fix: fenced code doesn't need a trailing newline

### LINKED ISSUE #2751: Dynamic data rendering with code block creates a flickering in dom
**Marked version:**
4.2.12
**Describe the bug**
Dynamic data rendering with code block creates a flickering in the dom.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=%60%60%60js%0Aconst%20hello%20%3D%20%27world%27%3B%0A%60%60%60&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

consider if the code block mentioned in the above link is inside a variable and the content is printing one by one. (you can reproduce this by typing a code block in this demo link) you can see a dom flickering issue because it is printing P tag first then after each new line it change to code block.

**Expected behavior**
It should work without any dom issue

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 4.2.12

## Description

Fenced code without closing ticks should consume the rest of the markdown. Currently it doesn't if there is no trailing newline character.

[marked demo](https://marked.js.org/demo/?text=%60%60%60%0Ademo&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.2.12)
[commonmark demo](https://spec.commonmark.org/dingus/?text=%60%60%60%0Ademo)

- Fixes #2751

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

File: lib/marked.cjs [hunk 1]
```diff
@@ -28,6 +28,20 @@ function _createClass(Constructor, protoProps, staticProps) {
   });
   return Constructor;
 }
+function _extends() {
```
Comment (calculuschild) [inline lib/marked.cjs:31]: What's the deal with `_extends` here? This appears to be replacing `merge()` but I thought #2730 already replaced that with the spread operator.

Also why are the bundled files appearing in this PR?

**Review by calculuschild — CHANGES_REQUESTED** [review]
Looks fine except I'm not following why this PR includes changes to the `/lib` files.

File: lib/marked.cjs (hunk 1 above)
Comment (UziTech) [reply lib/marked.cjs:31]: #2730 hasn't been merged yet. I included the lib folder so I could test the demo with this PR. The lib folder is rebuilt when released so it shouldn't matter if it is included in a PR.

I think the `_extends` method is added by roll-up.

**Review by calculuschild — APPROVED** [review]
