### PR TITLE
add walkTokens and fix highlight async

### LINKED ISSUE #1656: highlight callback is undefined
Latest version also prev. 0.8.x, when i run 
```ts
marked.setOptions({
            highlight: (code, language, callback) => {
                hljs.highlightAuto(code, [language])
                    .pipe(take(1))
                    .subscribe((highlight) => {
                        callback(null, highlight.value);
                    }, error => callback(error));
            }
        });
```
callback is refered as undefined

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 1.0.0

## Description

Using an async highlighting function was broken in v1.0.0 when we moved block tokens in blockquote and lists from the top level of the tokens array to a `tokens` property on the blockquote or listitem token.

This PR adds a public method to easily iterate over all tokens and send each token to a function specified by the user (`marked.walkTokens(tokens, callback)`) and uses that function to highlight code blocks asynchronously.

This also adds a `walkTokens` option so extensions can use it to run a function for each token.

**Example:** Overriding heading tokens to start at h2.

```js
const marked = require('marked');

// Override function
const walkTokens = (token) => {
  if (token.type === 'heading') {
    token.depth += 1;
  }
};

marked.use({ walkTokens });

// Run marked
console.log(marked('# heading 2\n\n## heading 3'));
```

**Output:**

```html
<h2 id="heading-2">heading 2</h2>
<h3 id="heading-3">heading 3</h3>
```

- Fixes #1656 

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression
- [x] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [x] Draft GitHub release notes have been updated.
- [x] CI is green (no forced merge required).
- [x] Merge PR

### CODE REVIEW

File: src/marked.js [hunk 1]
```diff
@@ -164,6 +154,50 @@ marked.use = function(extension) {
   marked.setOptions(opts);
 };
 
+/**
+ * Iterate over every token
+ */
+
+marked.iterateTokens = function(tokens, callback) {
```
Comment (UziTech) [inline src/marked.js:161]: I'm not sure what the best name for this function should be. A few names that I thought would be good:

- iterateTokens
- mapTokens (this might be confusing because we don't update the tokens based on the return value)
- updateTokens

/cc @styfle @joshbruce @davisjam

File: src/marked.js [hunk 2]
```diff
@@ -76,34 +70,30 @@ function marked(src, opt, callback) {
...
-    if (!pending) return done();
+    if (!tokens.length) return done();
 
-    for (; i < tokens.length; i++) {
-      (function(token) {
-        if (token.type !== 'code') {
-          return --pending || done();
-        }
-        return highlight(token.text, token.lang, function(err, code) {
-          if (err) return done(err);
```
Comment (UziTech) [inline src/marked.js:87]: I realized the callback sent to marked could be called multiple times because of this line. I'm not sure if that was intentional or a bug but I left it in case anyone relies on it being called for multiple highlighting errors.

File: src/marked.js [hunk 3]
```diff
@@ -164,6 +154,50 @@ marked.use = function(extension) {
...
+ * Iterate over every token
+ */
+
+marked.iterateTokens = function(tokens, callback) {
+  let ret;
+  for (const token of tokens) {
+    ret = callback(token);
+    if (ret === false) {
+      return false;
+    }
```
Comment (UziTech) [inline src/marked.js:167]: if the callback function returns `false` when iterating over the tokens the iterating will stop.

Comment (davisjam) [reply src/marked.js:167]: Is this a breaking change? AFAICT it would previously touch every token, and just eat failures?

File: src/marked.js (hunk 1 above)
Comment (davisjam) [reply src/marked.js:161]: iterateTokens seems fine

File: src/marked.js [hunk 4]
```diff
@@ -164,6 +154,50 @@ marked.use = function(extension) {
   marked.setOptions(opts);
 };
 
+/**
+ * Iterate over every token
```
Comment (davisjam) [inline src/marked.js:158]: Possibly worth documenting a few things here:

1. That this is recursive (could be a source of weird bugs on huge documents).
2. That the visit order is a pre-order DFS.
3. That if callback returns false, the iteration ceases.

File: src/marked.js (hunk 3 above)
Comment (UziTech) [reply src/marked.js:167]: The async highlighting still iterates over every token since it doesn't ever return `false`. I just added this to the new `iterateTokens` function so there is a way to stop if the user wants to.

This behavior is similar to other library functions such as [jquery.each](https://api.jquery.com/each/).

File: src/marked.js (hunk 1 above)
Comment (styfle) [reply src/marked.js:172]: I vote no for `mapTokens` because the return type is not an array of tokens.

I think `iterateTokens` is okay but maybe something like `walkTokens` would be better because it implies walking the tree recursively. https://en.wikipedia.org/wiki/Tree_traversal

Comment (davisjam) [reply src/marked.js:172]: Ah, I like `walkTokens`.

File: test/unit/marked-spec.js [hunk 5]
```diff
@@ -141,6 +153,29 @@ describe('use extension', () => {
...
+    const extension2 = {
+      walkTokens(token) {
+        walkedOnce++;
+        token.walkedOnce = true;
+      }
+    };
+    marked.use(extension1);
+    marked.use(extension2);
+    marked('text');
+    expect(walkedOnce).toBe(2);
```
Comment (styfle) [inline test/unit/marked-spec.js:175]: walkedOnce is 2? Maybe it should be renamed?

Comment (UziTech) [reply test/unit/marked-spec.js:175]: That variable counts how many tokens were walked at least once

Comment (davisjam) [reply test/unit/marked-spec.js:175]: Perhaps `nWalkedOnce` ?
